.TH man 3 "14 Oct 2017" "1.0" "OMP_DEBUG" man page

.SH NAME
OMP_DEBUG \- Enable debugging output

.SH DESCRIPTION
Enable debugging output. The variable should be set to 0 (disabled, also the default if not set), or 1 (enabled).
.br

.br
If enabled, some debugging output will be printed during execution. This is currently not specified in more detail, and subject to change.
