.TH man 3 "14 Oct 2017" "1.0" "OMP_WAIT_POLICY" man page

.SH NAME
OMP_WAIT_POLICY \- How waiting threads are handled

.SH DESCRIPTION
Specifies whether waiting threads should be active or passive.  If the value is PASSIVE, waiting threads should not consume CPU power while waiting; while the value is ACTIVE specifies that they should.  If undefined, threads wait actively for a short time before waiting passively.      

.SH SEE ALSO GOMP_SPINCOUNT(3)
