.TH man 3 "14 Oct 2017" "1.0" "OMP_CANCELLATION" man page

.SH NAME
OMP_CANCELLATION \- Set whether cancellation is activated

.SH DESCRIPTION
If set to TRUE, the cancellation is activated.  If set to FALSE or if unset, cancellation is disabled and the cancel construct is ignored.      

.SH SEE ALSO omp_get_cancellation(3)
