.TH man 3 "14 Oct 2017" "1.0" "OMP_DISPLAY_ENV" man page

.SH NAME
OMP_DISPLAY_ENV \- Show OpenMP version and environment variables

.SH DESCRIPTION
If set to TRUE, the OpenMP version number and the values associated with the OpenMP environment variables are printed to stderr.  If set to VERBOSE, it additionally shows the value of the environment variables which are GNU extensions.  If undefined or set to FALSE, this information will not be shown.      


