.TH man 3 "14 Oct 2017" "1.0" "OMP_THREAD_LIMIT" man page

.SH NAME
OMP_THREAD_LIMIT \- Set the maximum number of threads

.SH DESCRIPTION
Specifies the number of threads to use for the whole program.  The value of this variable shall be a positive integer.  If undefined, the number of threads is not limited.      

.SH SEE ALSO OMP_NUM_THREADS(3), omp_get_thread_limit(3)
