.TH man 3 "14 Oct 2017" "1.0" "OMP_NESTED" man page

.SH NAME
OMP_NESTED \- Nested parallel regions

.SH DESCRIPTION
Enable or disable nested parallel regions, i.e., whether team members are allowed to create new teams.  The value of this environment variable shall be TRUE or FALSE.  If undefined, nested parallel regions are disabled by default.      

.SH SEE ALSO omp_set_nested(3)
