.\" Manpage for omp_get_nested.
.TH man 3 "14 Oct 2017" "1.0" "omp_get_nested"

.SH NAME
omp_get_nested \- Nested parallel regions
.SH SYNOPSIS
.SS C/C++:
.br
#include<omp.h>
.br
int omp_get_nested(void);            

.SH Fortran:
.SS Interface:
.br
logical function omp_get_nested()            

.SH DESCRIPTION
This function returns true if nested parallel regions are enabled, false otherwise.  Here, true and false represent their language-specific counterparts.      Nested parallel regions may be initialized at startup by the OMP_NESTED environment variable or at runtime using omp_set_nested.  If undefined, nested parallel regions are disabled by default.      

.SH SEE ALSO omp_set_nested(3), OMP_NESTED(3)
