.\" Manpage for omp_get_num_devices.
.TH man 3 "14 Oct 2017" "1.0" "omp_get_num_devices"

.SH NAME
omp_get_num_devices \- Number of target devices
.SH SYNOPSIS
.SS C/C++:
.br
#include<omp.h>
.br
int omp_get_num_devices(void);            

.SH Fortran:
.SS Interface:
.br
integer function omp_get_num_devices()            

.SH DESCRIPTION
Returns the number of target devices.      


